apiVersion: v1
kind: Secret
metadata:
  name: de-dv-secrets
  namespace: de-dv
type: Opaque
data:
  KAFKA_SASL_USERNAME: <base64-placeholder>
  KAFKA_SASL_PASSWORD: <base64-placeholder>
  POSTGRES_USER: <base64-placeholder>
  POSTGRES_PASSWORD: <base64-placeholder>
  AWS_ACCESS_KEY_ID: <base64-placeholder>
  AWS_SECRET_ACCESS_KEY: <base64-placeholder>
  AIRFLOW__CORE__FERNET_KEY: <base64-placeholder>

