apiVersion: v1
kind: ConfigMap
metadata:
  name: cust-risk-pipeline

data:
  APP_NAME: cust-risk-triggers
  ENV: dev
  SPARK_MODE: batch
  DRIVER_MEMORY: 2g
  EXECUTOR_MEMORY: 4g
  EXECUTOR_CORES: "2"
  NUM_EXECUTORS: "3"

