services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      TUNNEL_METRICS: 0.0.0.0:2000
    depends_on:
      airflow-webserver:
        condition: service_healthy

