{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cust-risk-triggers.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.vault.enabled }}
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
    vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secretPath | quote }}
    {{- end }}
{{- end }}

